### PR TITLE
Toolbar and Headline Pull Request

### PR DESCRIPTION
**Pull request by PrantoshB**
- Add Toolbar and Headline section for Portfolio project

### CODE REVIEW

**Comment by PrantoshB** [comment]
I have fixed the two errors that the reviewer has marked.

Screenshot 2022-10-27 at 1 31 28 AM


Thanks

**Comment by PinkMoon25** [comment]
Hi @PrantoshB , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You do not have to reopen another pull request for the review, please submit the pull request that required changes and in which the previous code reviewer left suggestions, please keep in mind untill a pull request is accepted you submit the same PR for review and do not need to open another PR for review :+1: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

****_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._****

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by PrantoshB** [comment]
He told me to change the branch name.

So after changing the branch name, the previous pull request got deleted.

I searched online, but I couldn't find any way to change it while it's in
pull request.

So even if I have to create a new pull request, it'll be the same.

I hope you'll understand.

**Comment by PinkMoon25** [comment]
Hello @PrantoshB , As i can see the previous reviewer asked you to  consider adding a meaningful branch name for future projects, not changing the branch name for this current one.
the below note is always mentioned on a pull request :point_down: 
**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

Please try to keep this in mind for future projects as it helps in the code review flow and keeps the workflow smooth and profesional :pray:

**Comment by PrantoshB** [comment]
I have just opened that pull request and submitted for review.



Thanks

**Pull request merged**
